#!/usr/bin/env python3
"""Generates mock_wcdb.c from wcdb_sigs.json (the C ABI declared by the desktop app).

The mock stands in for libwcdb_api.so in tests. Functions echo their arguments as JSON
(`{"fn": "...", "args": [...]}`) so tests can verify argument marshalling, except a few
hand-written ones that return realistic chat data.
"""
import json, os, re

here = os.path.dirname(os.path.abspath(__file__))
sigs = json.load(open(os.path.join(here, 'wcdb_sigs.json')))

HAND_WRITTEN = {
    'wcdb_init', 'wcdb_shutdown', 'wcdb_open_account', 'wcdb_close_account', 'wcdb_free_string', 'wcdb_set_my_wxid',
    'wcdb_get_sessions', 'wcdb_get_messages', 'wcdb_get_contact', 'wcdb_get_group_nicknames', 'wcdb_get_group_members',
}

CTYPE = {'int32': 'int32_t', 'int64': 'int64_t'}

out = []
out.append('''// GENERATED by gen_mock.py - do not edit by hand.
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int ret_json(void** out, const char* s) {
    if (out) *out = strdup(s);
    return 0;
}

static size_t esc(char* dst, size_t cap, const char* src) {
    size_t n = 0;
    if (!src) { n += snprintf(dst + n, cap - n, "null"); return n; }
    n += snprintf(dst + n, cap - n, "\\"");
    for (; *src && n + 8 < cap; ++src) {
        unsigned char c = (unsigned char)*src;
        if (c == '"' || c == '\\\\') { dst[n++] = '\\\\'; dst[n++] = c; }
        else if (c == '\\n') { dst[n++] = '\\\\'; dst[n++] = 'n'; }
        else dst[n++] = c;
    }
    n += snprintf(dst + n, cap - n, "\\"");
    return n;
}

void wcdb_free_string(void* ptr) { free(ptr); }
int32_t wcdb_init(void) { return 0; }
int32_t wcdb_shutdown(void) { return 0; }
int32_t wcdb_open_account(const char* path, const char* key, int64_t* handle) {
    if (!path || !key || strlen(key) == 0) return -1;
    *handle = 1;
    return 0;
}
int32_t wcdb_close_account(int64_t handle) { return 0; }
int32_t wcdb_set_my_wxid(int64_t handle, const char* wxid) { return 0; }

int32_t wcdb_get_sessions(int64_t handle, void** out) {
    return ret_json(out, "[{\\"username\\":\\"wxid_bob\\",\\"summary\\":\\"hi\\"},{\\"username\\":\\"room1@chatroom\\"}]");
}

// Newest first, 3 rows at offset 0, nothing after.
int32_t wcdb_get_messages(int64_t handle, const char* session, int32_t limit, int32_t offset, void** out) {
    if (offset > 0) return ret_json(out, "[]");
    if (session && strstr(session, "chatroom")) {
        return ret_json(out,
            "[{\\"local_id\\":\\"3\\",\\"server_id\\":\\"9007199254740993\\",\\"create_time\\":\\"1700000120\\",\\"local_type\\":\\"1\\",\\"message_content\\":\\"wxid_bob:third\\",\\"sender_username\\":\\"wxid_bob\\",\\"is_send\\":\\"0\\"},"
            "{\\"local_id\\":\\"2\\",\\"create_time\\":\\"1700000060\\",\\"local_type\\":\\"1\\",\\"message_content\\":\\"second\\",\\"sender_username\\":\\"wxid_me\\",\\"is_send\\":\\"1\\"},"
            "{\\"local_id\\":\\"1\\",\\"create_time\\":\\"1700000000\\",\\"local_type\\":\\"10000\\",\\"message_content\\":\\"<sysmsg type=\\\\\\"x\\\\\\"><plain>Bob joined</plain></sysmsg>\\",\\"sender_username\\":\\"room1@chatroom\\",\\"is_send\\":\\"0\\"}]");
    }
    return ret_json(out,
        "[{\\"local_id\\":\\"3\\",\\"server_id\\":\\"9007199254740993\\",\\"create_time\\":\\"1700000120\\",\\"local_type\\":\\"3\\",\\"message_content\\":\\"\\",\\"sender_username\\":\\"wxid_bob\\",\\"is_send\\":\\"0\\"},"
        "{\\"local_id\\":\\"2\\",\\"create_time\\":\\"1700000060\\",\\"local_type\\":\\"1\\",\\"message_content\\":\\"wxid_bob:hi <there>\\",\\"sender_username\\":\\"wxid_bob\\",\\"is_send\\":\\"0\\"},"
        "{\\"local_id\\":\\"1\\",\\"create_time\\":\\"1700000000\\",\\"local_type\\":\\"1\\",\\"message_content\\":\\"hello, \\\\\\"world\\\\\\"\\",\\"is_send\\":\\"1\\"}]");
}

int32_t wcdb_get_contact(int64_t handle, const char* username, void** out) {
    if (username && strcmp(username, "wxid_bob") == 0)
        return ret_json(out, "{\\"username\\":\\"wxid_bob\\",\\"nickName\\":\\"Bob\\",\\"remark\\":\\"Bobby\\",\\"alias\\":\\"bb\\"}");
    if (username && strcmp(username, "wxid_me") == 0)
        return ret_json(out, "{\\"username\\":\\"wxid_me\\",\\"nickName\\":\\"Me Nick\\"}");
    return ret_json(out, "{}");
}

int32_t wcdb_get_group_nicknames(int64_t handle, const char* chatroom, void** out) {
    return ret_json(out, "{\\"wxid_bob\\":\\"Bob in room\\"}");
}

int32_t wcdb_get_group_members(int64_t handle, const char* chatroom, void** out) {
    return ret_json(out, "{\\"members\\":[{\\"username\\":\\"wxid_bob\\"},{\\"username\\":\\"wxid_me\\"},{\\"username\\":\\"wxid_quiet\\"}]}");
}
''')

for name, (ret, params) in sigs.items():
    if name in HAND_WRITTEN:
        continue
    decl = []
    body_args = []
    out_json = None
    post = []
    for i, p in enumerate(params):
        m = re.match(r'(.*?)(\w+)$', p.strip())
        ty, pname = m.group(1).strip(), m.group(2)
        if ty == '_Out_ void**':
            decl.append(f'void** {pname}'); out_json = pname
        elif ty == '_Out_ int32*':
            decl.append(f'int32_t* {pname}')
            post.append(f'if ({pname}) *{pname} = {"42" if "count" in pname.lower() else "0"};')
        elif ty == '_Out_ int64*':
            decl.append(f'int64_t* {pname}'); post.append(f'if ({pname}) *{pname} = 7;')
        elif ty == 'const char*':
            decl.append(f'const char* {pname}'); body_args.append(('s', pname))
        elif ty in CTYPE:
            decl.append(f'{CTYPE[ty]} {pname}'); body_args.append(('i64' if ty == 'int64' else 'i32', pname))
        else:
            raise SystemExit(f'unhandled param {p} in {name}')
    rtype = 'void' if ret == 'void' else 'int32_t'
    out.append(f'{rtype} {name}({", ".join(decl) or "void"}) {{')
    if ret == 'void':
        out.append('}\n')
        continue
    out.append('    char buf[16384]; size_t n = 0;')
    out.append(f'    n += snprintf(buf + n, sizeof(buf) - n, "{{\\"fn\\":\\"{name}\\",\\"args\\":[");')
    first = True
    for kind, pname in body_args:
        sep = '' if first else ','
        first = False
        if kind == 's':
            out.append(f'    n += snprintf(buf + n, sizeof(buf) - n, "{sep}"); n += esc(buf + n, sizeof(buf) - n, {pname});')
        elif kind == 'i64':
            out.append(f'    n += snprintf(buf + n, sizeof(buf) - n, "{sep}%lld", (long long){pname});')
        else:
            out.append(f'    n += snprintf(buf + n, sizeof(buf) - n, "{sep}%d", (int){pname});')
    out.append('    n += snprintf(buf + n, sizeof(buf) - n, "]}");')
    for line in post:
        out.append('    ' + line)
    if out_json:
        out.append(f'    return ret_json({out_json}, buf);')
    else:
        out.append('    return 0;')
    out.append('}\n')

open(os.path.join(here, 'mock_wcdb.c'), 'w').write('\n'.join(out))
print('wrote mock_wcdb.c')
