// GENERATED by gen_mock.py - do not edit by hand.
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static char g_last[16384];

// Test hook: JSON of the arguments of the most recent generated call.
const char* mock_last_call(void) { return g_last; }

static int ret_json(void** out, const char* s) {
    if (out) *out = strdup(s);
    return 0;
}

static size_t esc(char* dst, size_t cap, const char* src) {
    size_t n = 0;
    if (!src) { n += snprintf(dst + n, cap - n, "null"); return n; }
    n += snprintf(dst + n, cap - n, "\"");
    for (; *src && n + 8 < cap; ++src) {
        unsigned char c = (unsigned char)*src;
        if (c == '"' || c == '\\') { dst[n++] = '\\'; dst[n++] = c; }
        else if (c == '\n') { dst[n++] = '\\'; dst[n++] = 'n'; }
        else dst[n++] = c;
    }
    n += snprintf(dst + n, cap - n, "\"");
    return n;
}

void wcdb_free_string(void* ptr) { free(ptr); }
int32_t wcdb_init(void) { return 0; }
int32_t wcdb_shutdown(void) { return 0; }
int32_t wcdb_open_account(const char* path, const char* key, int64_t* handle) {
    if (!path || !key || strlen(key) == 0) return -1;
    *handle = 1;
    return 0;
}
int32_t wcdb_close_account(int64_t handle) { return 0; }
int32_t wcdb_set_my_wxid(int64_t handle, const char* wxid) { return 0; }

int32_t wcdb_get_sessions(int64_t handle, void** out) {
    return ret_json(out, "[{\"username\":\"wxid_bob\",\"summary\":\"hi\"},{\"username\":\"room1@chatroom\"}]");
}

// Newest first, 3 rows at offset 0, nothing after.
int32_t wcdb_get_messages(int64_t handle, const char* session, int32_t limit, int32_t offset, void** out) {
    if (offset > 0) return ret_json(out, "[]");
    if (session && strstr(session, "chatroom")) {
        return ret_json(out,
            "[{\"local_id\":\"3\",\"server_id\":\"9007199254740993\",\"create_time\":\"1700000120\",\"local_type\":\"1\",\"message_content\":\"wxid_bob:third\",\"sender_username\":\"wxid_bob\",\"is_send\":\"0\"},"
            "{\"local_id\":\"2\",\"create_time\":\"1700000060\",\"local_type\":\"1\",\"message_content\":\"second\",\"sender_username\":\"wxid_me\",\"is_send\":\"1\"},"
            "{\"local_id\":\"1\",\"create_time\":\"1700000000\",\"local_type\":\"10000\",\"message_content\":\"<sysmsg type=\\\"x\\\"><plain>Bob joined</plain></sysmsg>\",\"sender_username\":\"room1@chatroom\",\"is_send\":\"0\"}]");
    }
    return ret_json(out,
        "[{\"local_id\":\"3\",\"server_id\":\"9007199254740993\",\"create_time\":\"1700000120\",\"local_type\":\"3\",\"message_content\":\"\",\"sender_username\":\"wxid_bob\",\"is_send\":\"0\"},"
        "{\"local_id\":\"2\",\"create_time\":\"1700000060\",\"local_type\":\"1\",\"message_content\":\"wxid_bob:hi <there>\",\"sender_username\":\"wxid_bob\",\"is_send\":\"0\"},"
        "{\"local_id\":\"1\",\"create_time\":\"1700000000\",\"local_type\":\"1\",\"message_content\":\"hello, \\\"world\\\"\",\"is_send\":\"1\"}]");
}

int32_t wcdb_get_contact(int64_t handle, const char* username, void** out) {
    if (username && strcmp(username, "wxid_bob") == 0)
        return ret_json(out, "{\"username\":\"wxid_bob\",\"nickName\":\"Bob\",\"remark\":\"Bobby\",\"alias\":\"bb\"}");
    if (username && strcmp(username, "wxid_me") == 0)
        return ret_json(out, "{\"username\":\"wxid_me\",\"nickName\":\"Me Nick\"}");
    return ret_json(out, "{}");
}

int32_t wcdb_get_group_nicknames(int64_t handle, const char* chatroom, void** out) {
    return ret_json(out, "{\"wxid_bob\":\"Bob in room\"}");
}

int32_t wcdb_get_group_members(int64_t handle, const char* chatroom, void** out) {
    return ret_json(out, "{\"members\":[{\"username\":\"wxid_bob\"},{\"username\":\"wxid_me\"},{\"username\":\"wxid_quiet\"}]}");
}

int32_t wcdb_update_message(int64_t handle, const char* sessionId, int64_t localId, int32_t createTime, const char* newContent, void** outError) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_update_message\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, ",%lld", (long long)localId);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)createTime);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, newContent);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outError, buf);
}

int32_t wcdb_delete_message(int64_t handle, const char* sessionId, int64_t localId, int32_t createTime, const char* dbPathHint, void** outError) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_delete_message\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, ",%lld", (long long)localId);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)createTime);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, dbPathHint);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outError, buf);
}

int32_t wcdb_mark_all_sessions_read(int64_t handle, void** outError) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_mark_all_sessions_read\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outError, buf);
}

int32_t wcdb_get_message_count(int64_t handle, const char* username, int32_t* outCount) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_message_count\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, username);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    if (outCount) *outCount = 42;
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return 0;
}

int32_t wcdb_get_message_by_svrid(int64_t handle, const char* sessionId, const char* svrid, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_message_by_svrid\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, svrid);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "{\"local_id\":\"8\",\"server_id\":\"777\",\"create_time\":\"1700000060\",\"local_type\":\"1\",\"message_content\":\"found by svrid\",\"is_send\":\"1\"}");
}

int32_t wcdb_get_display_names(int64_t handle, const char* usernamesJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_display_names\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, usernamesJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "{\"wxid_bob\":\"Bobby\",\"wxid_me\":\"Me Nick\"}");
}

int32_t wcdb_get_avatar_urls(int64_t handle, const char* usernamesJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_avatar_urls\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, usernamesJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "{\"wxid_bob\":\"https://example.com/bob.png\"}");
}

int32_t wcdb_get_group_member_count(int64_t handle, const char* chatroomId, int32_t* outCount) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_group_member_count\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, chatroomId);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    if (outCount) *outCount = 42;
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return 0;
}

int32_t wcdb_get_group_member_counts(int64_t handle, const char* chatroomIdsJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_group_member_counts\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, chatroomIdsJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "{\"room1@chatroom\":3}");
}

int32_t wcdb_get_message_tables(int64_t handle, const char* sessionId, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_message_tables\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_message_meta(int64_t handle, const char* dbPath, const char* tableName, int32_t limit, int32_t offset, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_message_meta\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, dbPath);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, tableName);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)limit);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)offset);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_contact_status(int64_t handle, const char* usernamesJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_contact_status\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, usernamesJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "{\"wxid_bob\":{\"isFolded\":true,\"isMuted\":false}}");
}

int32_t wcdb_get_contact_type_counts(int64_t handle, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_contact_type_counts\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "{\"private\":2,\"group\":1,\"official\":1,\"former_friend\":0}");
}

int32_t wcdb_get_contacts_compact(int64_t handle, const char* usernamesJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_contacts_compact\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, usernamesJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "[{\"username\":\"wxid_bob\",\"local_type\":\"1\",\"nick_name\":\"Bob\",\"remark\":\"Bobby\"},{\"username\":\"wxid_carol\",\"local_type\":\"1\",\"nick_name\":\"Carol\"},{\"username\":\"wxid_me\",\"local_type\":\"1\"},{\"username\":\"gh_news\",\"local_type\":\"1\"},{\"username\":\"medianote\",\"local_type\":\"1\"},{\"username\":\"room1@chatroom\",\"local_type\":\"2\"}]");
}

int32_t wcdb_get_contact_alias_map(int64_t handle, const char* usernamesJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_contact_alias_map\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, usernamesJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_contact_friend_flags(int64_t handle, const char* usernamesJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_contact_friend_flags\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, usernamesJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_chat_room_ext_buffer(int64_t handle, const char* chatroomId, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_chat_room_ext_buffer\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, chatroomId);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_message_table_stats(int64_t handle, const char* sessionId, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_message_table_stats\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "[{\"db_path\":\"/x/message_0.db\",\"table_name\":\"Msg_abc\",\"count\":\"70\",\"first_timestamp\":\"1700000000\",\"last_timestamp\":\"1700009999\"},{\"db_path\":\"/x/message_1.db\",\"table_name\":\"Msg_abc\",\"count\":\"50\",\"first_timestamp\":\"1690000000\",\"last_timestamp\":\"1699999999\"}]");
}

int32_t wcdb_get_aggregate_stats(int64_t handle, const char* sessionIdsJson, int32_t begin, int32_t end, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_aggregate_stats\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionIdsJson);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)begin);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)end);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_available_years(int64_t handle, const char* sessionIdsJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_available_years\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionIdsJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_annual_report_stats(int64_t handle, const char* sessionIdsJson, int32_t begin, int32_t end, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_annual_report_stats\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionIdsJson);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)begin);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)end);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_annual_report_extras(int64_t handle, const char* sessionIdsJson, int32_t begin, int32_t end, int32_t peakBegin, int32_t peakEnd, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_annual_report_extras\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionIdsJson);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)begin);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)end);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)peakBegin);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)peakEnd);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_dual_report_stats(int64_t handle, const char* sessionId, int32_t begin, int32_t end, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_dual_report_stats\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)begin);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)end);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_logs(void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_logs\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_group_stats(int64_t handle, const char* chatroomId, int32_t begin, int32_t end, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_group_stats\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, chatroomId);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)begin);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)end);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "{\"sessions\":{\"room1@chatroom\":{\"senders\":{\"1\":30,\"2\":10,\"3\":5}}},\"idMap\":{\"1\":\"wxid_bob\",\"2\":\"wxid_me\",\"3\":\"wxid_quiet\"},\"hourly\":{\"9\":4,\"21\":7},\"typeCounts\":{\"1\":30,\"3\":5,\"47\":3,\"10000\":2,\"49\":4}}");
}

int32_t wcdb_get_my_footprint_stats(int64_t handle, const char* optionsJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_my_footprint_stats\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, optionsJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_message_dates(int64_t handle, const char* sessionId, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_message_dates\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "[\"2024-01-01\",\"2024-01-02\"]");
}

int32_t wcdb_open_message_cursor(int64_t handle, const char* sessionId, int32_t batchSize, int32_t ascending, int32_t beginTimestamp, int32_t endTimestamp, int64_t* outCursor) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_open_message_cursor\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)batchSize);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)ascending);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)beginTimestamp);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)endTimestamp);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    if (outCursor) *outCursor = 7;
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return 0;
}

int32_t wcdb_open_message_cursor_lite(int64_t handle, const char* sessionId, int32_t batchSize, int32_t ascending, int32_t beginTimestamp, int32_t endTimestamp, int64_t* outCursor) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_open_message_cursor_lite\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)batchSize);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)ascending);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)beginTimestamp);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)endTimestamp);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    if (outCursor) *outCursor = 7;
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return 0;
}

int32_t wcdb_fetch_message_batch(int64_t handle, int64_t cursor, void** outJson, int32_t* outHasMore) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_fetch_message_batch\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ",%lld", (long long)cursor);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    if (outHasMore) *outHasMore = 0;
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_close_message_cursor(int64_t handle, int64_t cursor) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_close_message_cursor\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ",%lld", (long long)cursor);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return 0;
}

int32_t wcdb_exec_query(int64_t handle, const char* kind, const char* path, const char* sql, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_exec_query\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, kind);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, path);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sql);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_emoticon_cdn_url(int64_t handle, const char* dbPath, const char* md5, void** outUrl) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_emoticon_cdn_url\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, dbPath);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, md5);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outUrl, buf);
}

int32_t wcdb_get_emoticon_caption(int64_t handle, const char* dbPath, const char* md5, void** outCaption) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_emoticon_caption\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, dbPath);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, md5);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outCaption, buf);
}

int32_t wcdb_get_emoticon_caption_strict(int64_t handle, const char* md5, void** outCaption) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_emoticon_caption_strict\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, md5);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outCaption, buf);
}

int32_t wcdb_list_message_dbs(int64_t handle, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_list_message_dbs\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_list_media_dbs(int64_t handle, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_list_media_dbs\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_message_by_id(int64_t handle, const char* sessionId, int32_t localId, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_message_by_id\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)localId);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "{\"local_id\":\"7\",\"server_id\":\"9007199254740993\",\"create_time\":\"1700000050\",\"local_type\":\"1\",\"message_content\":\"wxid_bob:found by id\",\"sender_username\":\"wxid_bob\",\"is_send\":\"0\"}");
}

int32_t wcdb_get_db_status(int64_t handle, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_db_status\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_voice_data(int64_t handle, const char* sessionId, int32_t createTime, int32_t localId, int64_t svrId, const char* candidatesJson, void** outHex) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_voice_data\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)createTime);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)localId);
    n += snprintf(buf + n, sizeof(buf) - n, ",%lld", (long long)svrId);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, candidatesJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outHex, buf);
}

int32_t wcdb_get_voice_data_batch(int64_t handle, const char* requestsJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_voice_data_batch\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, requestsJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_media_schema_summary(int64_t handle, const char* dbPath, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_media_schema_summary\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, dbPath);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_session_message_counts(int64_t handle, const char* sessionIdsJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_session_message_counts\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionIdsJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "{\"wxid_bob\":120,\"room1@chatroom\":55}");
}

int32_t wcdb_get_session_message_type_stats(int64_t handle, const char* sessionId, int32_t beginTimestamp, int32_t endTimestamp, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_session_message_type_stats\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)beginTimestamp);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)endTimestamp);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_session_message_type_stats_batch(int64_t handle, const char* sessionIdsJson, const char* optionsJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_session_message_type_stats_batch\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionIdsJson);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, optionsJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "{\"wxid_bob\":{\"total_messages\":120,\"voice_messages\":4,\"image_messages\":10,\"video_messages\":1,\"emoji_messages\":2,\"call_messages\":1,\"transfer_messages\":1,\"red_packet_messages\":0,\"first_timestamp\":1690000000,\"last_timestamp\":1700009999},\"room1@chatroom\":{\"total_messages\":55,\"voice_messages\":0,\"image_messages\":3,\"video_messages\":0,\"emoji_messages\":9,\"call_messages\":0,\"transfer_messages\":0,\"red_packet_messages\":2,\"first_timestamp\":1695000000,\"last_timestamp\":1700000000,\"group_my_messages\":17,\"group_sender_count\":3}}");
}

int32_t wcdb_get_session_message_date_counts(int64_t handle, const char* sessionId, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_session_message_date_counts\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "{\"2024-01-01\":3,\"2024-01-02\":0,\"2024-01-03\":5}");
}

int32_t wcdb_get_session_message_date_counts_batch(int64_t handle, const char* sessionIdsJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_session_message_date_counts_batch\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionIdsJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_messages_by_type(int64_t handle, const char* sessionId, int64_t localType, int32_t ascending, int32_t limit, int32_t offset, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_messages_by_type\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, ",%lld", (long long)localType);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)ascending);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)limit);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)offset);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "[{\"local_id\":\"11\",\"server_id\":\"5001\",\"create_time\":\"1700000300\",\"local_type\":\"3\",\"message_content\":\"<msg><img md5=\\\"aabbccddeeff00112233445566778899\\\" /></msg>\",\"sender_username\":\"wxid_bob\",\"is_send\":\"0\"},{\"local_id\":\"12\",\"create_time\":\"1700000200\",\"local_type\":\"3\",\"message_content\":\"<msg><img cdnmidimgurl=\\\"3057aabbccddeeff0011223344556677_xx.dat\\\" /></msg>\",\"sender_username\":\"wxid_bob\",\"is_send\":\"0\"},{\"local_id\":\"11\",\"server_id\":\"5001\",\"create_time\":\"1700000300\",\"local_type\":\"3\",\"message_content\":\"<msg><img md5=\\\"aabbccddeeff00112233445566778899\\\" /></msg>\",\"sender_username\":\"wxid_bob\",\"is_send\":\"0\"}]");
}

int32_t wcdb_scan_media_stream(int64_t handle, const char* sessionIdsJson, int32_t mediaType, int32_t beginTimestamp, int32_t endTimestamp, int32_t limit, int32_t offset, void** outJson, int32_t* outHasMore) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_scan_media_stream\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionIdsJson);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)mediaType);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)beginTimestamp);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)endTimestamp);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)limit);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)offset);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    if (outHasMore) *outHasMore = 0;
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_head_image_buffers(int64_t handle, const char* usernamesJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_head_image_buffers\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, usernamesJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_search_messages(int64_t handle, const char* sessionId, const char* keyword, int32_t limit, int32_t offset, int32_t beginTimestamp, int32_t endTimestamp, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_search_messages\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, keyword);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)limit);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)offset);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)beginTimestamp);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)endTimestamp);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_sns_timeline(int64_t handle, int32_t limit, int32_t offset, const char* username, const char* keyword, int32_t startTime, int32_t endTime, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_sns_timeline\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)limit);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)offset);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, username);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, keyword);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)startTime);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)endTime);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "[{\"id\":\"p1\",\"tid\":\"11\",\"username\":\"wxid_bob\",\"nickname\":\"\",\"createTime\":1700000500,\"contentDesc\":\"hello moments\",\"type\":1,\"rawXml\":\"<TimelineObject><location city=\\\"Shanghai\\\" poiName=\\\"Bund\\\" latitude=\\\"31.2\\\" longitude=\\\"121.5\\\"/></TimelineObject>\",\"media\":[{\"url\":\"http://mmsns.qpic.cn/a/150\",\"thumb\":\"http://mmsns.qpic.cn/a/150\",\"token\":\"TK\",\"md5\":\"abc\"}],\"likes\":[\"Carol\"],\"comments\":[{\"id\":\"1\",\"nickname\":\"Carol\",\"content\":\"nice\",\"refCommentId\":\"\",\"refNickname\":\"\"},{\"id\":\"2\",\"nickname\":\"Bob\",\"content\":\"thx\",\"refCommentId\":\"1\"}]},{\"id\":\"p2\",\"username\":\"wxid_carol\",\"nickname\":\"Carol\",\"createTime\":1700000400,\"contentDesc\":\"video\",\"type\":15,\"rawXml\":\"<x><enc key=\\\"2105122989\\\"/></x>\",\"media\":[{\"url\":\"http://snsvideodownload.qq.com/v?x=1\",\"thumb\":\"http://vweixinthumb.qpic.cn/t\",\"token\":\"T2\",\"key\":\"1\"}],\"likes\":[],\"comments\":[]}]");
}

int32_t wcdb_get_sns_annual_stats(int64_t handle, int32_t begin, int32_t end, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_sns_annual_stats\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)begin);
    n += snprintf(buf + n, sizeof(buf) - n, ",%d", (int)end);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_sns_usernames(int64_t handle, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_sns_usernames\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "[\"wxid_bob\",\"wxid_carol\"]");
}

int32_t wcdb_get_sns_export_stats(int64_t handle, const char* myWxid, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_sns_export_stats\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, myWxid);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, "{\"total_posts\":2,\"total_friends\":2,\"my_posts\":0}");
}

int32_t wcdb_get_message_table_columns(int64_t handle, const char* dbPath, const char* tableName, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_message_table_columns\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, dbPath);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, tableName);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_list_tables(int64_t handle, const char* kind, const char* dbPath, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_list_tables\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, kind);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, dbPath);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_table_schema(int64_t handle, const char* kind, const char* dbPath, const char* tableName, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_table_schema\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, kind);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, dbPath);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, tableName);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_export_table_snapshot(int64_t handle, const char* kind, const char* dbPath, const char* tableName, const char* outputPath, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_export_table_snapshot\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, kind);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, dbPath);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, tableName);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, outputPath);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_import_table_snapshot(int64_t handle, const char* kind, const char* dbPath, const char* tableName, const char* inputPath, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_import_table_snapshot\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, kind);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, dbPath);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, tableName);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, inputPath);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_import_table_snapshot_with_schema(int64_t handle, const char* kind, const char* dbPath, const char* tableName, const char* inputPath, const char* createTableSql, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_import_table_snapshot_with_schema\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, kind);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, dbPath);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, tableName);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, inputPath);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, createTableSql);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_get_message_table_time_range(int64_t handle, const char* dbPath, const char* tableName, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_message_table_time_range\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, dbPath);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, tableName);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_resolve_image_hardlink(int64_t handle, const char* md5, const char* accountDir, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_resolve_image_hardlink\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, md5);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, accountDir);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_resolve_image_hardlink_batch(int64_t handle, const char* requestsJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_resolve_image_hardlink_batch\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, requestsJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_resolve_video_hardlink_md5(int64_t handle, const char* md5, const char* dbPath, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_resolve_video_hardlink_md5\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, md5);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, dbPath);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_resolve_video_hardlink_md5_batch(int64_t handle, const char* requestsJson, void** outJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_resolve_video_hardlink_md5_batch\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, requestsJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outJson, buf);
}

int32_t wcdb_install_message_anti_revoke_trigger(int64_t handle, const char* sessionId, void** outError) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_install_message_anti_revoke_trigger\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outError, buf);
}

int32_t wcdb_uninstall_message_anti_revoke_trigger(int64_t handle, const char* sessionId, void** outError) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_uninstall_message_anti_revoke_trigger\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outError, buf);
}

int32_t wcdb_check_message_anti_revoke_trigger(int64_t handle, const char* sessionId, int32_t* outInstalled) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_check_message_anti_revoke_trigger\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, sessionId);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    if (outInstalled) *outInstalled = 0;
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return 0;
}

int32_t wcdb_install_sns_block_delete_trigger(int64_t handle, void** outError) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_install_sns_block_delete_trigger\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outError, buf);
}

int32_t wcdb_uninstall_sns_block_delete_trigger(int64_t handle, void** outError) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_uninstall_sns_block_delete_trigger\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outError, buf);
}

int32_t wcdb_check_sns_block_delete_trigger(int64_t handle, int32_t* outInstalled) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_check_sns_block_delete_trigger\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    if (outInstalled) *outInstalled = 0;
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return 0;
}

int32_t wcdb_delete_sns_post(int64_t handle, const char* postId, void** outError) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_delete_sns_post\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%lld", (long long)handle);
    n += snprintf(buf + n, sizeof(buf) - n, ","); n += esc(buf + n, sizeof(buf) - n, postId);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outError, buf);
}

int32_t wcdb_start_monitor_pipe(void) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_start_monitor_pipe\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return 0;
}

void wcdb_stop_monitor_pipe(void) {
}

int32_t wcdb_get_monitor_pipe_name(void** outName) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_get_monitor_pipe_name\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return ret_json(outName, buf);
}

int32_t wcdb_cloud_init(int32_t intervalSeconds) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_cloud_init\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, "%d", (int)intervalSeconds);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return 0;
}

int32_t wcdb_cloud_report(const char* statsJson) {
    char buf[16384]; size_t n = 0;
    n += snprintf(buf + n, sizeof(buf) - n, "{\"fn\":\"wcdb_cloud_report\",\"args\":[");
    n += snprintf(buf + n, sizeof(buf) - n, ""); n += esc(buf + n, sizeof(buf) - n, statsJson);
    n += snprintf(buf + n, sizeof(buf) - n, "]}");
    snprintf(g_last, sizeof(g_last), "%s", buf);
    return 0;
}

void wcdb_cloud_stop(void) {
}
