// Chinese help text: (English doc comment, Chinese). Keep in sync with the doc comments in main.rs; a test fails on gaps.
const HELP: &[(&str, &str)] = &[
    ("Show the wxid of the account(s) in the WeChat data directory (the value for `config set wxid`)", "显示微信数据目录中账号的 wxid（即 `config set wxid` 要填的值）"),
    ("WeChat data directory (default: `db_path` from the config, else the usual locations)", "微信数据目录（默认：配置中的 `db_path`，否则在常用位置查找）"),
    ("Show the path of the config file", "显示配置文件路径"),
    ("A page of one member's messages (newest first)", "某位成员的一页消息（最新在前）"),
    ("AI footprint summary; takes the JSON payload {rangeLabel, summary, privateSegments, mentionGroups}", "AI 足迹总结；接收 JSON 载荷 {rangeLabel, summary, privateSegments, mentionGroups}"),
    ("AI insights", "AI 洞察"),
    ("Access token for the HTTP API (default: `http_api_token` from the config)", "HTTP API 的访问令牌（默认：配置中的 `http_api_token`）"),
    ("Account directory to search for templates (default: the configured account directory)", "用于查找模板的账号目录（默认：已配置的账号目录）"),
    ("All image identifiers of a session (md5 / dat name), newest first", "会话的全部图片标识（md5 / dat 名），最新在前"),
    ("All voice messages of a session", "会话的全部语音消息"),
    ("Also save images / live photos / videos next to the export", "同时将图片 / 实况照片 / 视频保存在导出文件旁"),
    ("Annual and dual-person reports", "年度报告与双人报告"),
    ("Ask the server for the first bytes of a Moments resource and show the status and decryption headers", "向服务器请求朋友圈资源的前几个字节，并显示状态与解密头信息"),
    ("Bypass the 10-minute panel cache", "绕过 10 分钟的面板缓存"),
    ("Check whether a decoded voice WAV is already cached for a message id", "检查某条消息的语音 WAV 是否已解码并缓存"),
    ("Clear WeFlow's caches", "清理 WeFlow 的缓存"),
    ("Install and locate the ffmpeg for the few WXGF images the built-in decoder cannot read", "安装并查找 ffmpeg，用于内置解码器读不了的少数 WXGF 图片"),
    ("Download the ffmpeg build the desktop app bundles (ffmpeg-static b6.1.1), check its SHA-256 and unpack it into WeFlow's folder; used when FFMPEG_PATH is unset and no ffmpeg is on PATH", "下载桌面端自带的同一版本 ffmpeg（ffmpeg-static b6.1.1），校验 SHA-256 后解压到 WeFlow 的文件夹；未设置 FFMPEG_PATH 且 PATH 中没有 ffmpeg 时使用它"),
    ("Download it again even when the installed copy is intact", "即使已安装的副本完好也重新下载"),
    ("Change a setting of the ffmpeg download", "修改 ffmpeg 下载的设置"),
    ("Go back to the default of a setting of the ffmpeg download", "把 ffmpeg 下载的某项设置恢复为默认值"),
    ("Download from a mirror of the ffmpeg-static releases instead of GitHub, for example https://registry.npmmirror.com/-/binary/ffmpeg-static (the files are checked either way)", "从 ffmpeg-static 发布文件的镜像下载，而不是 GitHub，例如 https://registry.npmmirror.com/-/binary/ffmpeg-static（无论从哪里下载都会校验文件）"),
    ("Address the release folder `b6.1.1` is found under (http:// or https://)", "存放发布文件夹 `b6.1.1` 的地址（http:// 或 https://）"),
    ("Download from GitHub again", "恢复为从 GitHub 下载"),
    ("Show the ffmpeg those WXGF images use and where it was found (FFMPEG_PATH, PATH, installed or missing)", "显示这类 WXGF 图片使用的 ffmpeg 及其来源（FFMPEG_PATH、PATH、installed 或 missing）"),
    ("Save the output language", "保存输出语言"),
    ("Output language", "输出语言"),
    ("Set a key", "设置一个键"),
    ("Key name; `<profile>.<key>` (for example `work.wxid`) sets a key of another profile\n  db_path                  WeChat data directory (`db detect` finds it)\n  wxid                     Account wxid (`db wxid` prints it)\n  decrypt_key              Database key in hex (`key db` prints it)\n  image_xor_key            Image XOR key, a number (`key image` prints it)\n  image_aes_key            Image AES key (`key image` prints it)\n  cache_path               Folder for cached images, voices, stickers and Moments (default: `cache` next to the config file)\n  http_api_token           Access token of the HTTP API (`serve`)\n  http_api_host            Listen address of `serve` (default 127.0.0.1)\n  http_api_port            Listen port of `serve` (default 5031)\n  ai_model_api_base_url    Base URL of the AI model API used by `insight`\n  ai_model_api_key         API key of the AI model API\n  ai_model_api_model       Model name\n  ai_model_api_max_tokens  Most tokens in one AI reply\n  ai_insight_enabled       true or false: turn AI insight on or off\n  log_enabled              true or false; kept for the desktop app, the CLI does not read it\n  no_progress              true or false: true hides the automatic progress bar\n  progress_delay_seconds   Seconds a command runs before the progress bar appears (default 5; 0 = always)\nSettings of the config file itself (stored in that file, not in a profile; each config file has its own):\n  lang                     Output language, en or zh (the same as `weflow lang`)\n  current_profile          Active profile name, created when it does not exist (default: default)\nWhich config file is used (kept next to the default location, not in any config file):\n  config_path              Config file used from now on; `config unset config_path` or the default path switches back", "键名；`<档案>.<键>`（例如 `work.wxid`）可设置其他档案的键\n  db_path                  微信数据目录（`db detect` 可找到）\n  wxid                     账号 wxid（`db wxid` 会输出）\n  decrypt_key              十六进制的数据库密钥（`key db` 会输出）\n  image_xor_key            图片 XOR 密钥，一个数字（`key image` 会输出）\n  image_aes_key            图片 AES 密钥（`key image` 会输出）\n  cache_path               缓存图片、语音、表情和朋友圈的文件夹（默认：配置文件旁的 `cache`）\n  http_api_token           HTTP API 的访问令牌（`serve` 使用）\n  http_api_host            `serve` 的监听地址（默认 127.0.0.1）\n  http_api_port            `serve` 的监听端口（默认 5031）\n  ai_model_api_base_url    `insight` 使用的 AI 模型 API 的基础地址\n  ai_model_api_key         AI 模型 API 的密钥\n  ai_model_api_model       模型名称\n  ai_model_api_max_tokens  单次 AI 回复的最大 token 数\n  ai_insight_enabled       true 或 false：开启或关闭 AI 洞察\n  log_enabled              true 或 false；为桌面应用保留，命令行不读取\n  no_progress              true 或 false：true 时不显示自动进度条\n  progress_delay_seconds   命令运行多少秒后才显示进度条（默认 5；0 表示始终显示）\n配置文件自身的设置（保存在该配置文件里，不属于某个档案；每个配置文件各有一份）：\n  lang                     输出语言，en 或 zh（与 `weflow lang` 相同）\n  current_profile          当前档案名称，不存在时自动创建（默认：default）\n使用哪个配置文件（记录在默认位置旁，不写入任何配置文件）：\n  config_path              此后使用的配置文件；`config unset config_path` 或传入默认路径则恢复默认"),
    ("Use another config file from now on (the default location when given the default path)", "此后改用另一个配置文件（传入默认路径则恢复默认位置）"),
    ("Switch the active config profile (created when it does not exist)", "切换当前配置档案（不存在时自动创建）"),
    ("Comma-separated usernames that replace the list (pass \"\" to clear it)", "用逗号分隔的用户名，用于替换该列表（传入 \"\" 可清空）"),
    ("Contact counts per tab (friends, groups, official accounts, former friends)", "各标签页的联系人数量（好友、群聊、公众号、已删除好友）"),
    ("Contacts ranked by message count", "按消息数排序的联系人"),
    ("Conversation id: the other party's wxid, or xxx@chatroom for a group", "会话 ID：对方的 wxid，群聊则为 xxx@chatroom"),
    ("Conversation ids to download originals for (default: `autoDownloadWhitelist` from the config)", "需要下载原图的会话 ID（默认：配置中的 `autoDownloadWhitelist`）"),
    ("Conversation the image belongs to (locates msg/attach/<md5(session)>/…)", "图片所属的会话（用于定位 msg/attach/<md5(会话)>/…）"),
    ("Copy media next to the export and point the messages at the copies: any of image, voice, video, emoji (comma separated) or all. Files go to `media/<output name>/` beside the output file", "将媒体文件复制到导出文件旁，并让消息指向这些副本：可选 image、voice、video、emoji（逗号分隔）或 all。文件保存在输出文件旁的 `media/<输出名>/` 中"),
    ("Create, inspect and restore backups", "创建、查看和恢复备份"),
    ("Cursor returned as `nextCursor` by the previous page", "上一页返回的 `nextCursor` 游标"),
    ("Dates that have messages in a session (YYYY-MM-DD)", "会话中有消息的日期（YYYY-MM-DD）"),
    ("Decode and cache many voice messages; takes a JSON array of {localId, createTime, serverId?, senderWxid?}", "批量解码并缓存语音消息；接收 {localId, createTime, serverId?, senderWxid?} 的 JSON 数组"),
    ("Decode one voice message (SILK) into a 24 kHz WAV file", "将一条语音消息（SILK）解码为 24 kHz 的 WAV 文件"),
    ("Decrypt an image into the image cache. Without --force a cached thumbnail may be returned; with --force the HD original is used when it is on disk (`export media` always behaves like --force)", "将图片解密到图片缓存。不加 --force 时可能返回缓存的缩略图；加 --force 时若磁盘上有高清原图则使用原图（`export media` 始终按 --force 处理）"),
    ("Decrypt the image of one message and write it to a file", "解密一条消息的图片并写入文件"),
    ("Delete insight records (all, or filtered)", "删除洞察记录（全部或按条件）"),
    ("Derive the image keys from WeChat's kvcomm cache (verified against a .dat template)", "从微信的 kvcomm 缓存推导图片密钥（用 .dat 模板校验）"),
    ("Detect, scan and test WeChat database locations", "检测、扫描并测试微信数据库位置"),
    ("Do not fall back to scanning by .dat name", "不回退到按 .dat 文件名扫描"),
    ("Download a Moments sticker (plain or AES-GCM encrypted)", "下载朋友圈表情（明文或 AES-GCM 加密）"),
    ("Download an arbitrary image URL and decrypt it if it is a .dat payload", "下载任意图片 URL，若是 .dat 数据则解密"),
    ("Download and decrypt images / videos into the cache and inline them as data URLs", "下载并解密图片 / 视频到缓存，并以 data URL 内联"),
    ("Emit NDJSON progress events on stderr (machine-readable)", "在 stderr 输出 NDJSON 进度事件（机器可读）"),
    ("End date, local time, inclusive (YYYY-MM-DD)", "结束日期，本地时间，含当天（YYYY-MM-DD）"),
    ("Excel: compact columns (time, sender, type, content)", "Excel：精简列（时间、发送者、类型、内容）"),
    ("Export a member's messages (.csv or .xlsx)", "导出某位成员的消息（.csv 或 .xlsx）"),
    ("Export sessions, contacts, messages, footprint and media", "导出会话、联系人、消息、足迹和媒体"),
    ("Export statistics (total posts / friends / mine); --fast reads the cached counts only", "导出统计（总动态数 / 好友数 / 我的动态数）；--fast 只读取缓存的计数"),
    ("Export the images, voice (WAV), videos and stickers of messages", "导出消息中的图片、语音（WAV）、视频和表情"),
    ("Export the member list (.csv or .xlsx)", "导出成员列表（.csv 或 .xlsx）"),
    ("Export the messages of one conversation", "导出一个会话的消息"),
    ("Export the timeline as json, html or arkmejson", "将时间线导出为 json、html 或 arkmejson"),
    ("Extract database and image keys", "提取数据库密钥和图片密钥"),
    ("Extract the video md5 from a message XML payload", "从消息 XML 中提取视频 md5"),
    ("Fetch (and decrypt, with --key) a Moments image or video", "获取朋友圈图片或视频（使用 --key 时同时解密）"),
    ("First day (YYYY-MM-DD, local time)", "起始日期（YYYY-MM-DD，本地时间）"),
    ("Folded / muted state of sessions", "会话的折叠 / 免打扰状态"),
    ("Footprint statistics from the database", "来自数据库的足迹统计"),
    ("Generate a test insight for the first eligible private chat (or for --session)", "为第一个符合条件的私聊（或 --session 指定的会话）生成测试洞察"),
    ("Generate for this conversation instead of the first eligible one", "改为对该会话生成，而不是第一个符合条件的会话"),
    ("Group chat members and statistics", "群聊成员与统计"),
    ("Group chats with member counts", "带成员数的群聊"),
    ("Hook WeChat and keep the hook alive until interrupted (re-hooks after a WeChat restart)", "挂钩微信并保持挂钩直到被中断（微信重启后会重新挂钩）"),
    ("Hook WeChat and wait for the database key (Windows: keep the command running and log in to WeChat)", "挂钩微信并等待数据库密钥（Windows：保持命令运行，并登录微信）"),
    ("Hour / weekday / month distribution", "按小时 / 星期 / 月份的分布"),
    ("How long to wait for the key, in seconds", "等待密钥的时长（秒）"),
    ("How senders are named: group-nickname, remark or nickname (default: group-nickname, i.e. group nickname, then remark, nickname, wxid)", "发送者的命名方式：group-nickname、remark 或 nickname（默认：group-nickname，即依次取群昵称、备注、昵称、微信号）"),
    ("Import settings from the desktop app's config.json", "从桌面应用的 config.json 导入设置"),
    ("Include per-member message counts", "包含每位成员的消息数"),
    ("Last day, inclusive (YYYY-MM-DD)", "结束日期，含当天（YYYY-MM-DD）"),
    ("List image / video / voice / file messages across sessions", "列出所有会话中的图片 / 视频 / 语音 / 文件消息"),
    ("List insight records (newest first)", "列出洞察记录（最新在前）"),
    ("Listen address (default: `http_api_host` from the config, else 127.0.0.1)", "监听地址（默认：配置中的 `http_api_host`，否则为 127.0.0.1）"),
    ("Listen port (default: `http_api_port` from the config, else 5031)", "监听端口（默认：配置中的 `http_api_port`，否则为 5031）"),
    ("Local message id", "本地消息 ID"),
    ("Locate videos stored by WeChat and parse video md5s", "定位微信保存的视频并解析视频 md5"),
    ("Locate, decrypt and cache message images", "定位、解密并缓存消息图片"),
    ("Look an image up in the cache without decrypting", "在缓存中查找图片，不进行解密"),
    ("Look up one message by local id or server id", "按本地 ID 或服务器 ID 查找一条消息"),
    ("Look up the on-disk video (and optional cover/thumbnail) for a message md5", "按消息 md5 查找磁盘上的视频（以及可选的封面 / 缩略图）"),
    ("Mark all sessions as read", "将所有会话标为已读"),
    ("Members panel (friend flag, owner, group nickname, optional message counts)", "成员面板（好友标记、群主、群昵称，可选消息数）"),
    ("Message count per day for a session", "会话每天的消息数"),
    ("Message create time (seconds); selects the year-month folder", "消息创建时间（秒）；用于选择年月文件夹"),
    ("Message type mix", "消息类型构成"),
    ("Messages per hour of day", "每天各小时的消息数"),
    ("Moments (SNS) timeline, export and block-delete trigger", "朋友圈（SNS）时间线、导出与防删除触发器"),
    ("Moments timeline (newest first)", "朋友圈时间线（最新在前）"),
    ("Most active members", "最活跃的成员"),
    ("Native CLI for WeFlow", "WeFlow 原生命令行工具"),
    ("Official accounts and WeChat Pay records", "公众号与微信支付记录"),
    ("One member's statistics (types, hours, common phrases and emoji)", "某位成员的统计（类型、时段、常用语和表情）"),
    ("Only export messages sent by this person: their bare wxid, as `chat contacts` lists it (not an account folder name with a `_xxxx` suffix)", "仅导出这个人发送的消息：填裸 wxid，即 `chat contacts` 列出的形式（不能是带 `_xxxx` 后缀的账号文件夹名）"),
    ("Only media of this conversation id (default: all conversations)", "仅该会话 ID 的媒体（默认：所有会话）"),
    ("Only messages from this date, local time, inclusive (YYYY-MM-DD)", "仅该日期起的消息，本地时间，含当天（YYYY-MM-DD）"),
    ("Only messages up to this date, local time, inclusive (YYYY-MM-DD)", "仅截至该日期的消息，本地时间，含当天（YYYY-MM-DD）"),
    ("Only posts of these users (repeatable)", "仅这些用户的动态（可重复）"),
    ("Only the extra part (tables, first/latest time)", "仅附加部分（数据表、最早 / 最新时间）"),
    ("Only the fast part (contact info + message count)", "仅快速部分（联系人信息 + 消息数）"),
    ("Output WAV path (default: print base64 in the JSON result)", "输出 WAV 路径（默认：在 JSON 结果中输出 base64）"),
    ("Output directory", "输出目录"),
    ("Output file", "输出文件"),
    ("Overall chat statistics (private chats, honouring the exclusion list)", "整体聊天统计（私聊，遵循排除列表）"),
    ("Overall statistics, rankings and time distribution", "整体统计、排行与时间分布"),
    ("Page through image/video messages with the native media scanner", "用原生媒体扫描器分页浏览图片 / 视频消息"),
    ("Per-session statistics used by the export page", "导出页面使用的各会话统计"),
    ("Post counts per user, or the statistics of one user", "各用户的动态数，或某一用户的统计"),
    ("Prefer the HD rendition", "优先使用高清版本"),
    ("Print JSON (for scripts) instead of the human-readable output", "输出 JSON（供脚本使用），而不是便于阅读的文本"),
    ("Private chats that can be excluded from analytics", "可从统计中排除的私聊"),
    ("Read and write configuration", "读写配置"),
    ("Read or set the cached \"my message count\" of a group chat", "读取或设置群聊中缓存的“我的消息数”"),
    ("Read sessions, messages and contacts; anti-revoke triggers; media", "读取会话、消息和联系人；防撤回触发器；媒体"),
    ("Recompute instead of using the cached aggregate", "重新计算，而不是使用缓存的汇总数据"),
    ("Remove a key", "删除一个键"),
    ("Remove every key of the active profile", "删除当前档案的所有键"),
    ("Report year; 0 (default) covers all years", "报告年份；0（默认）表示所有年份"),
    ("Resolve many images; takes a JSON array of payloads (sessionId, imageMd5, imageDatName, createTime, …)", "批量解析图片；接收载荷的 JSON 数组（sessionId、imageMd5、imageDatName、createTime 等）"),
    ("Resolve payer / receiver display names of a transfer message", "解析转账消息的付款方 / 收款方显示名"),
    ("Return `file://` URLs instead of base64 data URLs for the posters", "封面返回 `file://` URL，而不是 base64 data URL"),
    ("Return a file path instead of a base64 data URL", "返回文件路径，而不是 base64 data URL"),
    ("Run the HTTP API, message push, insight and image auto-download services", "运行 HTTP API、消息推送、洞察和图片自动下载服务"),
    ("Run the silence scan once", "执行一次沉默扫描"),
    ("Scan WeChat's memory for the image AES key (macOS)", "在微信内存中扫描图片 AES 密钥（macOS）"),
    ("Sender wxid (important in group chats)", "发送者 wxid（群聊中很重要）"),
    ("Session details (contact info, message count, message tables, first/latest time)", "会话详情（联系人信息、消息数、消息表、最早 / 最新时间）"),
    ("Sessions that anti-revoke can be installed for", "可安装防撤回的会话"),
    ("Set a key. Main keys: db_path, wxid, decrypt_key, image_xor_key, image_aes_key, cache_path, http_api_token, http_api_host, http_api_port, ai_model_api_base_url, ai_model_api_key, ai_model_api_model, ai_model_api_max_tokens, ai_insight_enabled, no_progress, progress_delay_seconds (desktop names such as dbPath also work)", "设置一个键。主要键：db_path、wxid、decrypt_key、image_xor_key、image_aes_key、cache_path、http_api_token、http_api_host、http_api_port、ai_model_api_base_url、ai_model_api_key、ai_model_api_model、ai_model_api_max_tokens、ai_insight_enabled、no_progress、progress_delay_seconds（也支持桌面应用的名称，如 dbPath）"),
    ("Show every key of the active profile", "显示当前档案的所有键"),
    ("Show one key (or all when omitted)", "显示某个键（省略则显示全部）"),
    ("Show the embedded runtime and manifest", "显示内置运行时与清单"),
    ("Show the exclusion list, or replace it with --set", "显示排除列表，或用 --set 替换"),
    ("Skip cover / thumbnail images", "跳过封面 / 缩略图"),
    ("Skip mutual group / friend relations", "跳过共同群聊 / 共同好友关系"),
    ("Start date, local time (YYYY-MM-DD)", "开始日期，本地时间（YYYY-MM-DD）"),
    ("Start date, local time, inclusive (YYYY-MM-DD)", "开始日期，本地时间，含当天（YYYY-MM-DD）"),
    ("Test the AI model connection", "测试 AI 模型连接"),
    ("Today's trigger counts (only meaningful inside a running `serve --insight`)", "今日触发次数（仅在运行中的 `serve --insight` 内有意义）"),
    ("Total message counts for several sessions", "多个会话的消息总数"),
    ("Users that have posted", "发过动态的用户"),
    ("WeChat process id (default: the first Weixin.exe / WeChat.exe found)", "微信进程 ID（默认：找到的第一个 Weixin.exe / WeChat.exe）"),
    ("What to export: image, voice, video, emoji or all", "导出内容：image、voice、video、emoji 或 all"),
    ("Windows only: make WeChat download original-size images (img_helper.dll hook)", "仅限 Windows：让微信下载原图（img_helper.dll 挂钩）"),
    ("Words to exclude from the phrase rankings (repeatable)", "要从常用语排行中排除的词（可重复）"),
    ("image, video or all", "image、video 或 all"),
    ("image, video, voice, file (repeatable)", "image、video、voice、file（可重复）"),
    ("txt (default), json, arkme-json, chatlab, chatlab-jsonl, excel, weclone, html, sql", "txt（默认）、json、arkme-json、chatlab、chatlab-jsonl、excel、weclone、html、sql"),
    ("Value to store", "要保存的值"),
    ("Find WeChat data directories on this computer", "查找本机上的微信数据目录"),
    ("Scan a folder for WeChat account directories", "扫描文件夹中的微信账号目录"),
    ("Test that the configured database can be opened with the key", "测试能否用密钥打开已配置的数据库"),
    ("Open the configured database and show a short summary", "打开已配置的数据库并显示简要信息"),
    ("List conversations, newest first", "列出会话，最新在前"),
    ("Maximum number of sessions (0 = all)", "最多返回的会话数（0 表示全部）"),
    ("A page of a conversation's messages", "某个会话的一页消息"),
    ("The latest messages of a conversation", "某个会话的最新消息"),
    ("Number of messages", "消息条数"),
    ("Search the messages of one conversation or of all of them", "在某个会话或所有会话中搜索消息"),
    ("Text to search for", "要搜索的文字"),
    ("Only search this conversation (default: all conversations)", "只搜索这个会话（默认：所有会话）"),
    ("Maximum number of results", "最多返回的条数"),
    ("Number of results to skip", "跳过的条数"),
    ("Only messages from this time on (Unix seconds, 0 = no limit)", "只搜索这个时间之后的消息（Unix 秒，0 表示不限）"),
    ("Only messages up to this time (Unix seconds, 0 = no limit)", "只搜索到这个时间为止的消息（Unix 秒，0 表示不限）"),
    ("List all contacts", "列出所有联系人"),
    ("Show one contact", "显示一个联系人"),
    ("Contact username (wxid)", "联系人用户名（wxid）"),
    ("Edit a message (always refused: the database is read-only)", "修改消息（一律拒绝：数据库是只读的）"),
    ("Message create time (seconds)", "消息创建时间（秒）"),
    ("New message content", "新的消息内容"),
    ("Delete a message (always refused: the database is read-only)", "删除消息（一律拒绝：数据库是只读的）"),
    ("Database file the message is stored in", "消息所在的数据库文件"),
    ("Anti-revoke triggers (installing and removing are refused: the database is read-only)", "防撤回触发器（安装和卸载会被拒绝：数据库是只读的）"),
    ("Server message id", "服务器消息 ID"),
    ("Conversation ids", "会话 ID"),
    ("Conversation usernames", "会话用户名"),
    ("Group chat id (xxx@chatroom)", "群聊 ID（xxx@chatroom）"),
    ("Store this value as the \"my message count\"", "把这个值保存为“我的消息数”"),
    ("Only this conversation (default: all conversations)", "只看这个会话（默认：所有会话）"),
    ("Payer username (wxid)", "付款方用户名（wxid）"),
    ("Receiver username (wxid)", "收款方用户名（wxid）"),
    ("Export all voice messages of a conversation as WAV files", "把一个会话的全部语音消息导出为 WAV 文件"),
    ("Output directory (default: the current directory)", "输出目录（默认：当前目录）"),
    ("JSON array of {localId, createTime, serverId?, senderWxid?}", "{localId, createTime, serverId?, senderWxid?} 的 JSON 数组"),
    ("Download the stickers of a conversation", "下载一个会话中的表情"),
    ("Check whether the anti-revoke trigger is installed for sessions", "检查这些会话是否已安装防撤回触发器"),
    ("Install the anti-revoke trigger for sessions (refused: the database is read-only)", "为这些会话安装防撤回触发器（会被拒绝：数据库是只读的）"),
    ("Remove the anti-revoke trigger from sessions (refused: the database is read-only)", "移除这些会话的防撤回触发器（会被拒绝：数据库是只读的）"),
    ("Export the session list", "导出会话列表"),
    ("Only these conversations (repeatable; default: all)", "只导出这些会话（可重复；默认：全部）"),
    ("Export format (default: json)", "导出格式（默认：json）"),
    ("Export the contact list", "导出联系人列表"),
    ("Export the footprint statistics", "导出足迹统计"),
    ("Number of contacts", "联系人数量"),
    ("Number of members", "成员数量"),
    ("Member username (wxid)", "成员用户名（wxid）"),
    ("Annual report", "年度报告"),
    ("Dual-person report", "双人报告"),
    ("Years that have data for the annual report", "可以生成年度报告的年份"),
    ("Generate the annual report", "生成年度报告"),
    ("Generate the report for you and one friend", "为你和一位好友生成双人报告"),
    ("Friend's username (wxid)", "好友用户名（wxid）"),
    ("Number of posts", "动态条数"),
    ("Number of posts to skip", "跳过的动态条数"),
    ("Only posts containing this text", "只导出包含这段文字的动态"),
    ("Only posts from this time on (Unix seconds, 0 = no limit)", "只导出这个时间之后的动态（Unix 秒，0 表示不限）"),
    ("Only posts up to this time (Unix seconds, 0 = no limit)", "只导出到这个时间为止的动态（Unix 秒，0 表示不限）"),
    ("Resource URL", "资源地址"),
    ("Only read the cached counts", "只读取缓存的计数"),
    ("Statistics of this user only", "只看这个用户的统计"),
    ("Prefer the cached counts", "优先使用缓存的计数"),
    ("Export format: json, html or arkmejson", "导出格式：json、html 或 arkmejson"),
    ("Decryption key", "解密密钥"),
    ("Output file (default: print base64 in the result)", "输出文件（默认：在结果中输出 base64）"),
    ("Sticker URL", "表情地址"),
    ("URL of the encrypted sticker", "加密表情的地址"),
    ("AES key of the encrypted sticker", "加密表情的 AES 密钥"),
    ("Image URL", "图片地址"),
    ("Moments block-delete trigger (installing and removing are refused: the database is read-only)", "朋友圈防删除触发器（安装和卸载会被拒绝：数据库是只读的）"),
    ("check, install or uninstall", "check、install 或 uninstall"),
    ("Delete a Moments post (always refused: the database is read-only)", "删除一条朋友圈（一律拒绝：数据库是只读的）"),
    ("Post id", "动态 ID"),
    ("List official accounts", "列出公众号"),
    ("Messages of one official account", "某个公众号的消息"),
    ("Official account username", "公众号用户名"),
    ("WeChat Pay records", "微信支付记录"),
    ("Image md5 from the message", "消息中的图片 md5"),
    ("Image .dat file name", "图片 .dat 文件名"),
    ("Only look the file up in WeChat's hardlink index", "只通过微信的硬链接索引查找文件"),
    ("Show whether the image auto-download hook is running", "显示图片自动下载钩子是否在运行"),
    ("Video md5 from the message", "消息中的视频 md5"),
    ("Only records containing this text", "只看包含这段文字的记录"),
    ("Only this conversation", "只删除这个会话的记录"),
    ("Only records from this time on (Unix seconds)", "只删除这个时间之后的记录（Unix 秒）"),
    ("Only records up to this time (Unix seconds)", "只删除到这个时间为止的记录（Unix 秒）"),
    ("Maximum number of records", "最多返回的记录数"),
    ("Number of records to skip", "跳过的记录数"),
    ("Show one insight record", "显示一条洞察记录"),
    ("Record id", "记录 ID"),
    ("Mark an insight record as read", "把一条洞察记录标为已读"),
    ("JSON payload", "JSON 参数"),
    ("Serve the HTTP API", "提供 HTTP API"),
    ("Push new messages to HTTP clients (SSE)", "向 HTTP 客户端推送新消息（SSE）"),
    ("Run the AI insight engine", "运行 AI 洞察引擎"),
    ("Run the image auto-download hook (Windows only)", "运行图片自动下载钩子（仅限 Windows）"),
    ("Show where the runtime is unpacked and its version", "显示运行时的解压位置和版本"),
    ("List the files of the embedded runtime with sizes and hashes", "列出内置运行时的文件、大小和哈希"),
    ("Create a backup of the current account", "为当前账号创建备份"),
    ("Leave out the cached images", "不包含缓存的图片"),
    ("Leave out the cached voice files", "不包含缓存的语音"),
    ("Leave out the cached stickers", "不包含缓存的表情"),
    ("Show what a backup contains", "查看备份的内容"),
    ("Backup file", "备份文件"),
    ("Restore a backup into a folder", "把备份恢复到一个文件夹"),
    ("Key name (default: show every key)", "键名（默认：显示所有键）"),
    ("Key name", "键名"),
    ("Desktop app config.json (default: found in the usual locations)", "桌面应用的 config.json（默认：在常用位置查找）"),
    ("Folder to scan", "要扫描的文件夹"),
    ("Account directory (user directory) to scan for the image key", "要扫描图片密钥的账号目录"),
    ("JSON array of image payloads", "图片参数的 JSON 数组"),
    ("Message XML", "消息 XML"),
    ("Folder to restore into", "要恢复到的文件夹"),
    // weflow cache
    ("Show each part of the cache: the option of `cache clear` that removes it, its size and where it is", "显示缓存的各个部分：`cache clear` 清理它所用的选项、大小和位置"),
    ("Remove the chosen parts of the cache; shows what goes and asks [y/N] first", "清理选中的缓存部分；先列出将要删除的内容并询问 [y/N]"),
    ("Remove WeFlow's data of the current account and take the account out of this profile: its cached images, voices, stickers, Moments, analytics and key fingerprints, then db_path, wxid, decrypt_key and the image keys of the profile. Shows what goes and asks [y/N] first. WeChat's own files are never touched", "删除 WeFlow 中当前账号的数据，并把该账号移出当前配置档案：缓存的图片、语音、表情、朋友圈、统计和密钥指纹，以及档案中的 db_path、wxid、decrypt_key 和图片密钥。先列出将要删除的内容并询问 [y/N]。不会触碰微信自身的文件"),
    ("Folder of exports; files and folders named after the account are removed too (repeatable)", "导出文件夹；其中以账号命名的文件和文件夹也会被删除（可重复）"),
    ("Do not ask before removing", "删除前不再询问"),
    ("Decrypted images", "已解密的图片"),
    ("Decoded voice messages", "已解码的语音"),
    ("Stickers", "表情"),
    ("Images and videos of Moments", "朋友圈的图片和视频"),
    ("Analytics aggregate", "统计汇总"),
    ("Media exported and avatars pushed by the HTTP API", "HTTP API 导出的媒体和推送的头像"),
    ("Fingerprints of keys that worked (the next command checks the key again)", "校验通过的密钥指纹（下一条命令会重新校验密钥）"),
    ("Runtimes unpacked by other WeFlow versions (the running version's stays)", "其他 WeFlow 版本释放的运行时（保留当前版本）"),
    ("Every part above", "以上全部"),
];
